var jsonRestaurant = {
 "data":[
 {"name":"r1",
  "stars":4,
  "reviews":1000,
  "categories":["brunch","american","vegan"],
  "location":{"x":100,"y":-200}
 },
 {"name":"r2",
  "stars":1,
  "reviews":130,
  "categories":["american"],
  "location":{"x":190,"y":-82.02}
 },
 {"name":"r3",
  "stars":3,
  "reviews":100,
  "categories":["mexican"],
  "location":{"x":100,"y":104}
 },
 {"name":"r4",
  "stars":4,
  "reviews":100,
  "categories":["chinese"],
  "location":{"x":100,"y":-200}
 },
 {"name":"r5",
  "stars":3,
  "reviews":12000,
  "categories":["japanese","grill"],
  "location":{"x":190,"y":-82.02}
 },
 {"name":"r6",
  "stars":4,
  "reviews":100,
  "categories":["american","grill"],
  "location":{"x":-10,"y":-82.02}
 },
 ]
}